

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS" 
export const LOGOUT_FAILURE= "LOGOUT_FAILUE"

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';


export const SET_TRIPS_REQUEST = 'SET_TRIPS_REQUEST';
export const SET_TRIPS_SUCCESS = 'SET_TRIPS_SUCCESS';
export const SET_TRIPS_FAILURE = 'SET_TRIPS_FAILURE';


export const SET_TRIP_TYPE = "SET_TRIP_TYPE";
export const SET_ORIGIN = "SET_ORIGIN";
export const SET_DESTINATION = "SET_DESTINATION";
export const SET_DEPARTURE_DATE = "SET_DEPARTURE_DATE";
export const SET_RETURN_DATE = "SET_RETURN_DATE";
export const SET_NUMBER_OF_SEATS = "SET_NUMBER_OF_SEATS";
export const SET_TRIP_ID = "SET_TRIP_ID";
export const SET_USER_ID = "SET_USER_ID";
export const SET_LOADING = "SET_LOADING";



export const ADD_TRIP = "ADD_TRIP"
export const DELETE_TRIP = "DELETE_TRIP"


export const ADD_BOOKING = "ADD_BOOKING";
export const DELETE_BOOKING = "DELETE_BOOKING";
export const UPDATE_BOOKING = "UPDATE_BOOKING";

export const BOOKING_ERROR = "BOOKING_ERROR"

export const BOOKING_TICKET_GENERATED = "BOOKING_TICKET_GENERATED"